// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/setup": {
    params: {};
  };
  "/no-access": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/groceries": {
    params: {};
  };
  "/budget": {
    params: {};
  };
  "/budget/budgets": {
    params: {};
  };
  "/budget/recurring": {
    params: {};
  };
  "/debts": {
    params: {};
  };
  "/assets": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/restore-account": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/setup" | "/no-access" | "/dashboard" | "/groceries" | "/budget" | "/budget/budgets" | "/budget/recurring" | "/debts" | "/assets" | "/calendar" | "/settings" | "/restore-account";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/setup.tsx": {
    id: "routes/setup";
    page: "/setup";
  };
  "routes/no-access.tsx": {
    id: "routes/no-access";
    page: "/no-access";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/dashboard" | "/groceries" | "/budget" | "/budget/budgets" | "/budget/recurring" | "/debts" | "/assets" | "/calendar" | "/settings";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/groceries.tsx": {
    id: "routes/groceries";
    page: "/groceries";
  };
  "routes/budget.tsx": {
    id: "routes/budget";
    page: "/budget" | "/budget/budgets" | "/budget/recurring";
  };
  "routes/budget.transactions.tsx": {
    id: "routes/budget.transactions";
    page: "/budget";
  };
  "routes/budget.budgets.tsx": {
    id: "routes/budget.budgets";
    page: "/budget/budgets";
  };
  "routes/budget.recurring.tsx": {
    id: "routes/budget.recurring";
    page: "/budget/recurring";
  };
  "routes/debts.tsx": {
    id: "routes/debts";
    page: "/debts";
  };
  "routes/assets.tsx": {
    id: "routes/assets";
    page: "/assets";
  };
  "routes/calendar.tsx": {
    id: "routes/calendar";
    page: "/calendar";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/restore-account.tsx": {
    id: "routes/restore-account";
    page: "/restore-account";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/setup": typeof import("./app/routes/setup.tsx");
  "routes/no-access": typeof import("./app/routes/no-access.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/groceries": typeof import("./app/routes/groceries.tsx");
  "routes/budget": typeof import("./app/routes/budget.tsx");
  "routes/budget.transactions": typeof import("./app/routes/budget.transactions.tsx");
  "routes/budget.budgets": typeof import("./app/routes/budget.budgets.tsx");
  "routes/budget.recurring": typeof import("./app/routes/budget.recurring.tsx");
  "routes/debts": typeof import("./app/routes/debts.tsx");
  "routes/assets": typeof import("./app/routes/assets.tsx");
  "routes/calendar": typeof import("./app/routes/calendar.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/restore-account": typeof import("./app/routes/restore-account.tsx");
};